"""Add is_onboarded

Revision ID: 32edf36d164d
Revises: d674073ec3ff
Create Date: 2026-05-17 18:51:31.481753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32edf36d164d'
down_revision = 'd674073ec3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_onboarded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_onboarded')

    # ### end Alembic commands ###
