"""Add chat history, meal plans, ml predictions, and exercise embeddings

Revision ID: 5ce0d85bb1e9
Revises: 182f382506e1
Create Date: 2026-05-19 14:46:43.672790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ce0d85bb1e9'
down_revision = '182f382506e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=200), nullable=False),
    sa.Column('muscle_group', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_embeddings')),
    sa.UniqueConstraint('exercise_name', name=op.f('uq_exercise_embeddings_exercise_name'))
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=False),
    sa.Column('diet_type', sa.String(length=100), nullable=True),
    sa.Column('breakfast', sa.Text(), nullable=True),
    sa.Column('lunch', sa.Text(), nullable=True),
    sa.Column('dinner', sa.Text(), nullable=True),
    sa.Column('snacks', sa.Text(), nullable=True),
    sa.Column('proteins', sa.String(length=50), nullable=True),
    sa.Column('carbs', sa.String(length=50), nullable=True),
    sa.Column('fats', sa.String(length=50), nullable=True),
    sa.Column('meal_timing', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plans'))
    )
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.String(length=100), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('output_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ml_predictions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_predictions'))
    )
    op.drop_table('consistency_scores')
    op.drop_table('weight_predictions')
    op.drop_table('generated_workout_plans')
    op.drop_table('recovery_scores')
    with op.batch_alter_table('ai_chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=20), nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('sender')

    op.create_table('recovery_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('soreness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sleep', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('intensity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recovery_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_scores'))
    )
    op.create_table('generated_workout_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('weekly_split', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cardio_plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progression_strategy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plan_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_generated_workout_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_workout_plans'))
    )
    op.create_table('weight_predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('predicted_7d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('predicted_30d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('predicted_90d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weight_predictions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_predictions'))
    )
    op.create_table('consistency_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dropout_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('streak_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skipped_workouts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('app_activity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consistency_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consistency_scores'))
    )
    op.drop_table('ml_predictions')
    op.drop_table('meal_plans')
    op.drop_table('exercise_embeddings')
    # ### end Alembic commands ###
